AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  RegionMap:
    us-east-1:
      vpcId: # Fill in your VPC ID
      subnetId: # Fill in your Subnet ID
      imageId: ami-03d315ad33b9d49c4
    us-east-2:
      vpcId: # Fill in your VPC ID
      subnetId: # Fill in your Subnet ID
      imageId: ami-0996d3051b72b5b2c
    us-west-2:
      vpcId: # Fill in your VPC ID
      subnetId: # Fill in your Subnet ID
      imageId: ami-0928f4202481dfdf6
    us-west-1:
      vpcId: # Fill in your VPC ID
      subnetId: # Fill in your Subnet ID
      imageId: ami-0ebef2838fb2605b7
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC2LaunchTemplate
      LaunchTemplateData:
        InstanceType: t3.nano
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: True
            SubnetId: !FindInMap [ RegionMap, !Ref "AWS::Region", subnetId ]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            /usr/bin/apt-get update -y
            /usr/bin/apt-get install -y python3-pip
            python3 -m pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-2.0-9.tar.gz
            /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets default --region ${AWS::Region}
            /usr/local/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", imageId ]
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
        Count: '1'
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - install
            - config
            - launch
        install:
          sources:
            /etc/cloudwatchagent: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
          commands:
            installCloudwatch:
              command: ./install.sh
              cwd: /etc/cloudwatchagent
        config:
          files:
            /opt/aws/amazon-cloudwatch-agent/amazon-cloudwatch-agent.json:
              # Add your configuration file here
        launch:
          commands:
            launchCloudwatch:
              command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/amazon-cloudwatch-agent.json -s
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleCloudWatch
  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Stelligent-U 08 CloudWatch'
      VpcId: !FindInMap [ RegionMap, !Ref "AWS::Region", vpcId ]
